### ISSUE TITLE
Pouvoir importer un fichier édité pour GoGoCartoJS dans GoGoCarto

### ISSUE THREAD

**Issue by tech62** [pixelhumain/GoGoCarto#25]
Y-a t'il une prévision d'ajout d'une fonction permettant de pouvoir importer un fichier édité pour GoGoCartoJS dans GoGoCarto ?

Merci !

**Comment by seballot** [comment]
Salut! Désolé, je ne comprends pas la question: de quel fichier parles tu? de la config en Json?

**Comment by tech62** [comment]
Bonjour, je parlais de pouvoir importer les fichiers contenant les POI et catégories présents sur la carte (taxonomy et results.js) dans GoGoCarto pour pouvoir utiliser le panel d'administration à la place de fichier plats

**Comment by seballot** [comment]
Ah ok ! oui c'est possible pour les POI, pas encore pour la taxonomy ! on peut importer des fichiers CSV ou Json si ils sont déjà au bon format. C'est encore un peu en dev mais ça sera bientôt disponible!
