### ISSUE TITLE
où l'installer ?

### ISSUE THREAD

**Issue by djulien19** [pixelhumain/GoGoCarto#26]
Bonjour,

J'aimerais installer Gogocarto pour un quartier de Paris afin de mettre en évidence plusieurs thématiques.
J'ai vu que la bdd est en Mongodb, et je trouve peu de serveurs en location avec cette gestion. Que recommanderiez-vous à des prix compétitifs ?
Merci d'avance et bravo pour ce projet que j'ai pu tester sur presdecheznous.fr
Julien

**Comment by seballot** [comment]
Salut Julien,
Non je n'ai rien de particulier à te proposer, désolé !

Mais on est en train mettre en place nu service en ligne pour que chacun puisse créer sa carte sans installer sur son serveur. Faut juste être un peu patient !

Qu'entendez tu par "mettre en évidence plusieurs thémtiques" ? si ce sont des thématiques déjà sur près de chez nous, tu sais que tu peux extraire une sous carte de pres de chez nous à intégrer sur un autre site en iframe?

**Comment by djulien19** [comment]
D’accord merci pour le retour rapide !
Super pour le service en ligne, à quel moment sera-t-il disponible ? Fin
d’année sûr ?
Pour les thématiques il s’agit de : sécurité, propreté, … pas en line avec
les catégories existantes sur presdecheznous

A bientôt,
Julien

Le 17 septembre 2018 à 09:46:44, Sebastian Castro (notifications@github.com)
a écrit:

Salut Julien,
Non je n'ai rien de particulier à te proposer, désolé !

Mais on est en train mettre en place nu service en ligne pour que chacun
puisse créer sa carte sans installer sur son serveur. Faut juste être un
peu patient !

Qu'entendez tu par "mettre en évidence plusieurs thémtiques" ? si ce sont
des thématiques déjà sur près de chez nous, tu sais que tu peux extraire
une sous carte de pres de chez nous à intégrer sur un autre site en iframe?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pixelhumain/GoGoCarto/issues/26#issuecomment-421917536>,
or mute the thread

**Comment by seballot** [comment]
pas de date fixe prévue pour le service en ligne, quand ce sera prêt ! mais oui d'ici quelques mois
