### ISSUE TITLE
Impossible de s'inscrire sur  RocketChat 

### ISSUE THREAD

**Issue by bablukid** [pixelhumain/GoGoCarto#33]
Hello, je voulais discuter avec les devs de gogoCarto, mais je ne peux pas m'inscrire sur RocketChat....

Tant que j'y suis , mes questions : 

Je suis le lead dev de Cagette.net, et j'ai découvert GogoCarto via le Transiscope.

Nous aimerions améliorer notre carte des groupes cagette ( https://app.cagette.net/group/map ) et je me demandais si gogoCarto ferait l'affaire.

Pour le coté front, ça m'a l'air de bien convenir à ce qu'on recherche : on aimerait pouvoir chercher des producteurs, des groupes Cagette en fonction de plusieurs critères.

Ma question porte plutot sur le backend : j'ai vu que le transiscope permet d'aggréger des données depuis plusieurs sources ( avec solid ? ),  est ce que gogoCarto PHP fait ça ou c'est un dev closed source qu'ils ont fait ?
L'idée serait que notre base de données de groupes Cagette et de producteurs soient interopérable et utilisable par d'autres plateformes, par exemple le transiscope.

**Comment by bablukid** [comment]
Super , merci pour toutes ces infos ! 

tu participes à quels groupes Cagette ?

**Comment by seballot** [comment]
Je suis co président de l'écolieu Jeanot dans les Landes (pas trop loin de vous, vous êtes à bordeaux non?), et ma compagne s'occupe de l'épicerie de la maison Garbay, qui participe aussi via Jeanot

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
